export const FETCH_REVIEWS = 'FETCH_REVIEWS';
export const REQUEST_REVIEWS_START = 'REQUEST_REVIEWS_START';
export const REQUEST_REVIEWS_SUCCESS = 'REQUEST_REVIEWS_SUCCESS';
export const REQUEST_REVIEWS_FAILURE = 'REQUEST_REVIEWS_FAILURE';

export const LOAD_MORE_REVIEWS_START = 'LOAD_MORE_REVIEWS_START';
export const LOAD_MORE_REVIEWS_SUCCESS = 'LOAD_MORE_REVIEWS_SUCCESS';
export const LOAD_MORE_REVIEWS_FAILURE = 'LOAD_MORE_REVIEWS_FAILURE';

export const FETCH_REVIEW_BY_ID_START = 'FETCH_REVIEW_BY_ID_START';
export const FETCH_REVIEW_BY_ID_SUCCESS = 'FETCH_REVIEW_BY_ID_SUCCESS';
export const FETCH_REVIEW_BY_ID_FAILURE = 'FETCH_REVIEW_BY_ID_FAILURE';

export const SEARCH_REVIEW = 'SEARCH_REVIEW';

export const SET_DATA_LOADING = 'SET_DATA_LOADING';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';


